#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Escritorio.DATOS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Software_Dog")]
	public partial class DBDogDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertDetalle(Detalle instance);
    partial void UpdateDetalle(Detalle instance);
    partial void DeleteDetalle(Detalle instance);
    partial void InsertDog_Vacu(Dog_Vacu instance);
    partial void UpdateDog_Vacu(Dog_Vacu instance);
    partial void DeleteDog_Vacu(Dog_Vacu instance);
    partial void InsertDogs(Dogs instance);
    partial void UpdateDogs(Dogs instance);
    partial void DeleteDogs(Dogs instance);
    partial void InsertFactura(Factura instance);
    partial void UpdateFactura(Factura instance);
    partial void DeleteFactura(Factura instance);
    partial void InsertInfo_Dog(Info_Dog instance);
    partial void UpdateInfo_Dog(Info_Dog instance);
    partial void DeleteInfo_Dog(Info_Dog instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertProveedor(Proveedor instance);
    partial void UpdateProveedor(Proveedor instance);
    partial void DeleteProveedor(Proveedor instance);
    partial void InsertRazas(Razas instance);
    partial void UpdateRazas(Razas instance);
    partial void DeleteRazas(Razas instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertVacunacion(Vacunacion instance);
    partial void UpdateVacunacion(Vacunacion instance);
    partial void DeleteVacunacion(Vacunacion instance);
    #endregion
		
		public DBDogDataContext() : 
				base(global::Proyecto_Escritorio.Properties.Settings.Default.Software_DogConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDogDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDogDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDogDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDogDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Categoria> Categoria
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Detalle> Detalle
		{
			get
			{
				return this.GetTable<Detalle>();
			}
		}
		
		public System.Data.Linq.Table<Dog_Vacu> Dog_Vacu
		{
			get
			{
				return this.GetTable<Dog_Vacu>();
			}
		}
		
		public System.Data.Linq.Table<Dogs> Dogs
		{
			get
			{
				return this.GetTable<Dogs>();
			}
		}
		
		public System.Data.Linq.Table<Factura> Factura
		{
			get
			{
				return this.GetTable<Factura>();
			}
		}
		
		public System.Data.Linq.Table<Info_Dog> Info_Dog
		{
			get
			{
				return this.GetTable<Info_Dog>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Producto
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Proveedor> Proveedor
		{
			get
			{
				return this.GetTable<Proveedor>();
			}
		}
		
		public System.Data.Linq.Table<Razas> Razas
		{
			get
			{
				return this.GetTable<Razas>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Vacunacion> Vacunacion
		{
			get
			{
				return this.GetTable<Vacunacion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categoria")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_categoria;
		
		private string _nombre_categoria;
		
		private EntitySet<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void Onnombre_categoriaChanging(string value);
    partial void Onnombre_categoriaChanged();
    #endregion
		
		public Categoria()
		{
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_categoria", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_categoria
		{
			get
			{
				return this._nombre_categoria;
			}
			set
			{
				if ((this._nombre_categoria != value))
				{
					this.Onnombre_categoriaChanging(value);
					this.SendPropertyChanging();
					this._nombre_categoria = value;
					this.SendPropertyChanged("nombre_categoria");
					this.Onnombre_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Producto", Storage="_Producto", ThisKey="id_categoria", OtherKey="id_categoria")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cedula_cliente;
		
		private string _nombre_cliente;
		
		private string _apellido_cliente;
		
		private string _direccion_cliente;
		
		private string _telefono_cliente;
		
		private string _correo_cliente;
		
		private EntitySet<Factura> _Factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncedula_clienteChanging(string value);
    partial void Oncedula_clienteChanged();
    partial void Onnombre_clienteChanging(string value);
    partial void Onnombre_clienteChanged();
    partial void Onapellido_clienteChanging(string value);
    partial void Onapellido_clienteChanged();
    partial void Ondireccion_clienteChanging(string value);
    partial void Ondireccion_clienteChanged();
    partial void Ontelefono_clienteChanging(string value);
    partial void Ontelefono_clienteChanged();
    partial void Oncorreo_clienteChanging(string value);
    partial void Oncorreo_clienteChanged();
    #endregion
		
		public Cliente()
		{
			this._Factura = new EntitySet<Factura>(new Action<Factura>(this.attach_Factura), new Action<Factura>(this.detach_Factura));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula_cliente", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cedula_cliente
		{
			get
			{
				return this._cedula_cliente;
			}
			set
			{
				if ((this._cedula_cliente != value))
				{
					this.Oncedula_clienteChanging(value);
					this.SendPropertyChanging();
					this._cedula_cliente = value;
					this.SendPropertyChanged("cedula_cliente");
					this.Oncedula_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_cliente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_cliente
		{
			get
			{
				return this._nombre_cliente;
			}
			set
			{
				if ((this._nombre_cliente != value))
				{
					this.Onnombre_clienteChanging(value);
					this.SendPropertyChanging();
					this._nombre_cliente = value;
					this.SendPropertyChanged("nombre_cliente");
					this.Onnombre_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_cliente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido_cliente
		{
			get
			{
				return this._apellido_cliente;
			}
			set
			{
				if ((this._apellido_cliente != value))
				{
					this.Onapellido_clienteChanging(value);
					this.SendPropertyChanging();
					this._apellido_cliente = value;
					this.SendPropertyChanged("apellido_cliente");
					this.Onapellido_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_cliente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string direccion_cliente
		{
			get
			{
				return this._direccion_cliente;
			}
			set
			{
				if ((this._direccion_cliente != value))
				{
					this.Ondireccion_clienteChanging(value);
					this.SendPropertyChanging();
					this._direccion_cliente = value;
					this.SendPropertyChanged("direccion_cliente");
					this.Ondireccion_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_cliente", DbType="VarChar(10)")]
		public string telefono_cliente
		{
			get
			{
				return this._telefono_cliente;
			}
			set
			{
				if ((this._telefono_cliente != value))
				{
					this.Ontelefono_clienteChanging(value);
					this.SendPropertyChanging();
					this._telefono_cliente = value;
					this.SendPropertyChanged("telefono_cliente");
					this.Ontelefono_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_cliente", DbType="VarChar(10)")]
		public string correo_cliente
		{
			get
			{
				return this._correo_cliente;
			}
			set
			{
				if ((this._correo_cliente != value))
				{
					this.Oncorreo_clienteChanging(value);
					this.SendPropertyChanging();
					this._correo_cliente = value;
					this.SendPropertyChanged("correo_cliente");
					this.Oncorreo_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Factura", Storage="_Factura", ThisKey="cedula_cliente", OtherKey="cedula_cliente")]
		public EntitySet<Factura> Factura
		{
			get
			{
				return this._Factura;
			}
			set
			{
				this._Factura.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detalle")]
	public partial class Detalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Detalle;
		
		private int _id_factura;
		
		private int _cod_articulo;
		
		private int _cantidad;
		
		private decimal _precio;
		
		private int _cod_dog;
		
		private EntityRef<Dogs> _Dogs;
		
		private EntityRef<Factura> _Factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_DetalleChanging(int value);
    partial void Onid_DetalleChanged();
    partial void Onid_facturaChanging(int value);
    partial void Onid_facturaChanged();
    partial void Oncod_articuloChanging(int value);
    partial void Oncod_articuloChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void OnprecioChanging(decimal value);
    partial void OnprecioChanged();
    partial void Oncod_dogChanging(int value);
    partial void Oncod_dogChanged();
    #endregion
		
		public Detalle()
		{
			this._Dogs = default(EntityRef<Dogs>);
			this._Factura = default(EntityRef<Factura>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Detalle", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_Detalle
		{
			get
			{
				return this._id_Detalle;
			}
			set
			{
				if ((this._id_Detalle != value))
				{
					this.Onid_DetalleChanging(value);
					this.SendPropertyChanging();
					this._id_Detalle = value;
					this.SendPropertyChanged("id_Detalle");
					this.Onid_DetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_factura", DbType="Int NOT NULL")]
		public int id_factura
		{
			get
			{
				return this._id_factura;
			}
			set
			{
				if ((this._id_factura != value))
				{
					if (this._Factura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_facturaChanging(value);
					this.SendPropertyChanging();
					this._id_factura = value;
					this.SendPropertyChanged("id_factura");
					this.Onid_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_articulo", DbType="Int NOT NULL")]
		public int cod_articulo
		{
			get
			{
				return this._cod_articulo;
			}
			set
			{
				if ((this._cod_articulo != value))
				{
					this.Oncod_articuloChanging(value);
					this.SendPropertyChanging();
					this._cod_articulo = value;
					this.SendPropertyChanged("cod_articulo");
					this.Oncod_articuloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(18,0) NOT NULL")]
		public decimal precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_dog", DbType="Int NOT NULL")]
		public int cod_dog
		{
			get
			{
				return this._cod_dog;
			}
			set
			{
				if ((this._cod_dog != value))
				{
					if (this._Dogs.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_dogChanging(value);
					this.SendPropertyChanging();
					this._cod_dog = value;
					this.SendPropertyChanged("cod_dog");
					this.Oncod_dogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dogs_Detalle", Storage="_Dogs", ThisKey="cod_dog", OtherKey="cod_dog", IsForeignKey=true)]
		public Dogs Dogs
		{
			get
			{
				return this._Dogs.Entity;
			}
			set
			{
				Dogs previousValue = this._Dogs.Entity;
				if (((previousValue != value) 
							|| (this._Dogs.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dogs.Entity = null;
						previousValue.Detalle.Remove(this);
					}
					this._Dogs.Entity = value;
					if ((value != null))
					{
						value.Detalle.Add(this);
						this._cod_dog = value.cod_dog;
					}
					else
					{
						this._cod_dog = default(int);
					}
					this.SendPropertyChanged("Dogs");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_Detalle", Storage="_Factura", ThisKey="id_factura", OtherKey="id_factura", IsForeignKey=true)]
		public Factura Factura
		{
			get
			{
				return this._Factura.Entity;
			}
			set
			{
				Factura previousValue = this._Factura.Entity;
				if (((previousValue != value) 
							|| (this._Factura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Factura.Entity = null;
						previousValue.Detalle.Remove(this);
					}
					this._Factura.Entity = value;
					if ((value != null))
					{
						value.Detalle.Add(this);
						this._id_factura = value.id_factura;
					}
					else
					{
						this._id_factura = default(int);
					}
					this.SendPropertyChanged("Factura");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dog_Vacu")]
	public partial class Dog_Vacu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dogvac;
		
		private int _cod_dog;
		
		private int _id_vacunacion;
		
		private System.DateTime _fecha;
		
		private EntityRef<Dogs> _Dogs;
		
		private EntityRef<Vacunacion> _Vacunacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_dogvacChanging(int value);
    partial void Onid_dogvacChanged();
    partial void Oncod_dogChanging(int value);
    partial void Oncod_dogChanged();
    partial void Onid_vacunacionChanging(int value);
    partial void Onid_vacunacionChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    #endregion
		
		public Dog_Vacu()
		{
			this._Dogs = default(EntityRef<Dogs>);
			this._Vacunacion = default(EntityRef<Vacunacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dogvac", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_dogvac
		{
			get
			{
				return this._id_dogvac;
			}
			set
			{
				if ((this._id_dogvac != value))
				{
					this.Onid_dogvacChanging(value);
					this.SendPropertyChanging();
					this._id_dogvac = value;
					this.SendPropertyChanged("id_dogvac");
					this.Onid_dogvacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_dog", DbType="Int NOT NULL")]
		public int cod_dog
		{
			get
			{
				return this._cod_dog;
			}
			set
			{
				if ((this._cod_dog != value))
				{
					if (this._Dogs.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_dogChanging(value);
					this.SendPropertyChanging();
					this._cod_dog = value;
					this.SendPropertyChanged("cod_dog");
					this.Oncod_dogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vacunacion", DbType="Int NOT NULL")]
		public int id_vacunacion
		{
			get
			{
				return this._id_vacunacion;
			}
			set
			{
				if ((this._id_vacunacion != value))
				{
					if (this._Vacunacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_vacunacionChanging(value);
					this.SendPropertyChanging();
					this._id_vacunacion = value;
					this.SendPropertyChanged("id_vacunacion");
					this.Onid_vacunacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dogs_Dog_Vacu", Storage="_Dogs", ThisKey="cod_dog", OtherKey="cod_dog", IsForeignKey=true)]
		public Dogs Dogs
		{
			get
			{
				return this._Dogs.Entity;
			}
			set
			{
				Dogs previousValue = this._Dogs.Entity;
				if (((previousValue != value) 
							|| (this._Dogs.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dogs.Entity = null;
						previousValue.Dog_Vacu.Remove(this);
					}
					this._Dogs.Entity = value;
					if ((value != null))
					{
						value.Dog_Vacu.Add(this);
						this._cod_dog = value.cod_dog;
					}
					else
					{
						this._cod_dog = default(int);
					}
					this.SendPropertyChanged("Dogs");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vacunacion_Dog_Vacu", Storage="_Vacunacion", ThisKey="id_vacunacion", OtherKey="id_vacunacion", IsForeignKey=true)]
		public Vacunacion Vacunacion
		{
			get
			{
				return this._Vacunacion.Entity;
			}
			set
			{
				Vacunacion previousValue = this._Vacunacion.Entity;
				if (((previousValue != value) 
							|| (this._Vacunacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vacunacion.Entity = null;
						previousValue.Dog_Vacu.Remove(this);
					}
					this._Vacunacion.Entity = value;
					if ((value != null))
					{
						value.Dog_Vacu.Add(this);
						this._id_vacunacion = value.id_vacunacion;
					}
					else
					{
						this._id_vacunacion = default(int);
					}
					this.SendPropertyChanged("Vacunacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dogs")]
	public partial class Dogs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_dog;
		
		private string _nombre_dog;
		
		private int _cod_raza;
		
		private string _color_dog;
		
		private decimal _precio_dog;
		
		private string _origen_dog;
		
		private string _sexo_dog;
		
		private string _pedigree;
		
		private System.DateTime _fecha_nacimiento;
		
		private EntitySet<Detalle> _Detalle;
		
		private EntitySet<Dog_Vacu> _Dog_Vacu;
		
		private EntityRef<Razas> _Razas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_dogChanging(int value);
    partial void Oncod_dogChanged();
    partial void Onnombre_dogChanging(string value);
    partial void Onnombre_dogChanged();
    partial void Oncod_razaChanging(int value);
    partial void Oncod_razaChanged();
    partial void Oncolor_dogChanging(string value);
    partial void Oncolor_dogChanged();
    partial void Onprecio_dogChanging(decimal value);
    partial void Onprecio_dogChanged();
    partial void Onorigen_dogChanging(string value);
    partial void Onorigen_dogChanged();
    partial void Onsexo_dogChanging(string value);
    partial void Onsexo_dogChanged();
    partial void OnpedigreeChanging(string value);
    partial void OnpedigreeChanged();
    partial void Onfecha_nacimientoChanging(System.DateTime value);
    partial void Onfecha_nacimientoChanged();
    #endregion
		
		public Dogs()
		{
			this._Detalle = new EntitySet<Detalle>(new Action<Detalle>(this.attach_Detalle), new Action<Detalle>(this.detach_Detalle));
			this._Dog_Vacu = new EntitySet<Dog_Vacu>(new Action<Dog_Vacu>(this.attach_Dog_Vacu), new Action<Dog_Vacu>(this.detach_Dog_Vacu));
			this._Razas = default(EntityRef<Razas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_dog", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cod_dog
		{
			get
			{
				return this._cod_dog;
			}
			set
			{
				if ((this._cod_dog != value))
				{
					this.Oncod_dogChanging(value);
					this.SendPropertyChanging();
					this._cod_dog = value;
					this.SendPropertyChanged("cod_dog");
					this.Oncod_dogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_dog", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_dog
		{
			get
			{
				return this._nombre_dog;
			}
			set
			{
				if ((this._nombre_dog != value))
				{
					this.Onnombre_dogChanging(value);
					this.SendPropertyChanging();
					this._nombre_dog = value;
					this.SendPropertyChanged("nombre_dog");
					this.Onnombre_dogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_raza", DbType="Int NOT NULL")]
		public int cod_raza
		{
			get
			{
				return this._cod_raza;
			}
			set
			{
				if ((this._cod_raza != value))
				{
					if (this._Razas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_razaChanging(value);
					this.SendPropertyChanging();
					this._cod_raza = value;
					this.SendPropertyChanged("cod_raza");
					this.Oncod_razaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color_dog", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string color_dog
		{
			get
			{
				return this._color_dog;
			}
			set
			{
				if ((this._color_dog != value))
				{
					this.Oncolor_dogChanging(value);
					this.SendPropertyChanging();
					this._color_dog = value;
					this.SendPropertyChanged("color_dog");
					this.Oncolor_dogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_dog", DbType="Decimal(18,0) NOT NULL")]
		public decimal precio_dog
		{
			get
			{
				return this._precio_dog;
			}
			set
			{
				if ((this._precio_dog != value))
				{
					this.Onprecio_dogChanging(value);
					this.SendPropertyChanging();
					this._precio_dog = value;
					this.SendPropertyChanged("precio_dog");
					this.Onprecio_dogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_origen_dog", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string origen_dog
		{
			get
			{
				return this._origen_dog;
			}
			set
			{
				if ((this._origen_dog != value))
				{
					this.Onorigen_dogChanging(value);
					this.SendPropertyChanging();
					this._origen_dog = value;
					this.SendPropertyChanged("origen_dog");
					this.Onorigen_dogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo_dog", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string sexo_dog
		{
			get
			{
				return this._sexo_dog;
			}
			set
			{
				if ((this._sexo_dog != value))
				{
					this.Onsexo_dogChanging(value);
					this.SendPropertyChanging();
					this._sexo_dog = value;
					this.SendPropertyChanged("sexo_dog");
					this.Onsexo_dogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pedigree", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string pedigree
		{
			get
			{
				return this._pedigree;
			}
			set
			{
				if ((this._pedigree != value))
				{
					this.OnpedigreeChanging(value);
					this.SendPropertyChanging();
					this._pedigree = value;
					this.SendPropertyChanged("pedigree");
					this.OnpedigreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="Date NOT NULL")]
		public System.DateTime fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this.Onfecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento = value;
					this.SendPropertyChanged("fecha_nacimiento");
					this.Onfecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dogs_Detalle", Storage="_Detalle", ThisKey="cod_dog", OtherKey="cod_dog")]
		public EntitySet<Detalle> Detalle
		{
			get
			{
				return this._Detalle;
			}
			set
			{
				this._Detalle.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dogs_Dog_Vacu", Storage="_Dog_Vacu", ThisKey="cod_dog", OtherKey="cod_dog")]
		public EntitySet<Dog_Vacu> Dog_Vacu
		{
			get
			{
				return this._Dog_Vacu;
			}
			set
			{
				this._Dog_Vacu.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Razas_Dogs", Storage="_Razas", ThisKey="cod_raza", OtherKey="cod_raza", IsForeignKey=true)]
		public Razas Razas
		{
			get
			{
				return this._Razas.Entity;
			}
			set
			{
				Razas previousValue = this._Razas.Entity;
				if (((previousValue != value) 
							|| (this._Razas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Razas.Entity = null;
						previousValue.Dogs.Remove(this);
					}
					this._Razas.Entity = value;
					if ((value != null))
					{
						value.Dogs.Add(this);
						this._cod_raza = value.cod_raza;
					}
					else
					{
						this._cod_raza = default(int);
					}
					this.SendPropertyChanged("Razas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle(Detalle entity)
		{
			this.SendPropertyChanging();
			entity.Dogs = this;
		}
		
		private void detach_Detalle(Detalle entity)
		{
			this.SendPropertyChanging();
			entity.Dogs = null;
		}
		
		private void attach_Dog_Vacu(Dog_Vacu entity)
		{
			this.SendPropertyChanging();
			entity.Dogs = this;
		}
		
		private void detach_Dog_Vacu(Dog_Vacu entity)
		{
			this.SendPropertyChanging();
			entity.Dogs = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Factura")]
	public partial class Factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_factura;
		
		private string _cedula_cliente;
		
		private string _ruc;
		
		private EntitySet<Detalle> _Detalle;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Info_Dog> _Info_Dog;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_facturaChanging(int value);
    partial void Onid_facturaChanged();
    partial void Oncedula_clienteChanging(string value);
    partial void Oncedula_clienteChanged();
    partial void OnrucChanging(string value);
    partial void OnrucChanged();
    #endregion
		
		public Factura()
		{
			this._Detalle = new EntitySet<Detalle>(new Action<Detalle>(this.attach_Detalle), new Action<Detalle>(this.detach_Detalle));
			this._Cliente = default(EntityRef<Cliente>);
			this._Info_Dog = default(EntityRef<Info_Dog>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_factura", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_factura
		{
			get
			{
				return this._id_factura;
			}
			set
			{
				if ((this._id_factura != value))
				{
					this.Onid_facturaChanging(value);
					this.SendPropertyChanging();
					this._id_factura = value;
					this.SendPropertyChanged("id_factura");
					this.Onid_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula_cliente", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string cedula_cliente
		{
			get
			{
				return this._cedula_cliente;
			}
			set
			{
				if ((this._cedula_cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncedula_clienteChanging(value);
					this.SendPropertyChanging();
					this._cedula_cliente = value;
					this.SendPropertyChanged("cedula_cliente");
					this.Oncedula_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ruc", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ruc
		{
			get
			{
				return this._ruc;
			}
			set
			{
				if ((this._ruc != value))
				{
					if (this._Info_Dog.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrucChanging(value);
					this.SendPropertyChanging();
					this._ruc = value;
					this.SendPropertyChanged("ruc");
					this.OnrucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_Detalle", Storage="_Detalle", ThisKey="id_factura", OtherKey="id_factura")]
		public EntitySet<Detalle> Detalle
		{
			get
			{
				return this._Detalle;
			}
			set
			{
				this._Detalle.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Factura", Storage="_Cliente", ThisKey="cedula_cliente", OtherKey="cedula_cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Factura.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Factura.Add(this);
						this._cedula_cliente = value.cedula_cliente;
					}
					else
					{
						this._cedula_cliente = default(string);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Info_Dog_Factura", Storage="_Info_Dog", ThisKey="ruc", OtherKey="ruc", IsForeignKey=true)]
		public Info_Dog Info_Dog
		{
			get
			{
				return this._Info_Dog.Entity;
			}
			set
			{
				Info_Dog previousValue = this._Info_Dog.Entity;
				if (((previousValue != value) 
							|| (this._Info_Dog.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Info_Dog.Entity = null;
						previousValue.Factura.Remove(this);
					}
					this._Info_Dog.Entity = value;
					if ((value != null))
					{
						value.Factura.Add(this);
						this._ruc = value.ruc;
					}
					else
					{
						this._ruc = default(string);
					}
					this.SendPropertyChanged("Info_Dog");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle(Detalle entity)
		{
			this.SendPropertyChanging();
			entity.Factura = this;
		}
		
		private void detach_Detalle(Detalle entity)
		{
			this.SendPropertyChanging();
			entity.Factura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Info_Dog")]
	public partial class Info_Dog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _emp_Id;
		
		private string _ruc;
		
		private string _nombre;
		
		private string _direccion;
		
		private EntitySet<Factura> _Factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onemp_IdChanging(int value);
    partial void Onemp_IdChanged();
    partial void OnrucChanging(string value);
    partial void OnrucChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    #endregion
		
		public Info_Dog()
		{
			this._Factura = new EntitySet<Factura>(new Action<Factura>(this.attach_Factura), new Action<Factura>(this.detach_Factura));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int emp_Id
		{
			get
			{
				return this._emp_Id;
			}
			set
			{
				if ((this._emp_Id != value))
				{
					this.Onemp_IdChanging(value);
					this.SendPropertyChanging();
					this._emp_Id = value;
					this.SendPropertyChanged("emp_Id");
					this.Onemp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ruc", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ruc
		{
			get
			{
				return this._ruc;
			}
			set
			{
				if ((this._ruc != value))
				{
					this.OnrucChanging(value);
					this.SendPropertyChanging();
					this._ruc = value;
					this.SendPropertyChanged("ruc");
					this.OnrucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Info_Dog_Factura", Storage="_Factura", ThisKey="ruc", OtherKey="ruc")]
		public EntitySet<Factura> Factura
		{
			get
			{
				return this._Factura;
			}
			set
			{
				this._Factura.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Info_Dog = this;
		}
		
		private void detach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Info_Dog = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_articulo;
		
		private string _descripcion_articulo;
		
		private int _cantidad_articulo;
		
		private decimal _precio_articulo;
		
		private int _id_categoria;
		
		private int _id_proveedor;
		
		private EntityRef<Categoria> _Categoria;
		
		private EntityRef<Proveedor> _Proveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_articuloChanging(int value);
    partial void Oncod_articuloChanged();
    partial void Ondescripcion_articuloChanging(string value);
    partial void Ondescripcion_articuloChanged();
    partial void Oncantidad_articuloChanging(int value);
    partial void Oncantidad_articuloChanged();
    partial void Onprecio_articuloChanging(decimal value);
    partial void Onprecio_articuloChanged();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void Onid_proveedorChanging(int value);
    partial void Onid_proveedorChanged();
    #endregion
		
		public Producto()
		{
			this._Categoria = default(EntityRef<Categoria>);
			this._Proveedor = default(EntityRef<Proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_articulo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cod_articulo
		{
			get
			{
				return this._cod_articulo;
			}
			set
			{
				if ((this._cod_articulo != value))
				{
					this.Oncod_articuloChanging(value);
					this.SendPropertyChanging();
					this._cod_articulo = value;
					this.SendPropertyChanged("cod_articulo");
					this.Oncod_articuloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_articulo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string descripcion_articulo
		{
			get
			{
				return this._descripcion_articulo;
			}
			set
			{
				if ((this._descripcion_articulo != value))
				{
					this.Ondescripcion_articuloChanging(value);
					this.SendPropertyChanging();
					this._descripcion_articulo = value;
					this.SendPropertyChanged("descripcion_articulo");
					this.Ondescripcion_articuloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad_articulo", DbType="Int NOT NULL")]
		public int cantidad_articulo
		{
			get
			{
				return this._cantidad_articulo;
			}
			set
			{
				if ((this._cantidad_articulo != value))
				{
					this.Oncantidad_articuloChanging(value);
					this.SendPropertyChanging();
					this._cantidad_articulo = value;
					this.SendPropertyChanged("cantidad_articulo");
					this.Oncantidad_articuloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_articulo", DbType="Decimal(18,0) NOT NULL")]
		public decimal precio_articulo
		{
			get
			{
				return this._precio_articulo;
			}
			set
			{
				if ((this._precio_articulo != value))
				{
					this.Onprecio_articuloChanging(value);
					this.SendPropertyChanging();
					this._precio_articulo = value;
					this.SendPropertyChanged("precio_articulo");
					this.Onprecio_articuloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int NOT NULL")]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					if (this._Categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proveedor", DbType="Int NOT NULL")]
		public int id_proveedor
		{
			get
			{
				return this._id_proveedor;
			}
			set
			{
				if ((this._id_proveedor != value))
				{
					if (this._Proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_proveedorChanging(value);
					this.SendPropertyChanging();
					this._id_proveedor = value;
					this.SendPropertyChanged("id_proveedor");
					this.Onid_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Producto", Storage="_Categoria", ThisKey="id_categoria", OtherKey="id_categoria", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._id_categoria = value.id_categoria;
					}
					else
					{
						this._id_categoria = default(int);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proveedor_Producto", Storage="_Proveedor", ThisKey="id_proveedor", OtherKey="Id_proveedor", IsForeignKey=true)]
		public Proveedor Proveedor
		{
			get
			{
				return this._Proveedor.Entity;
			}
			set
			{
				Proveedor previousValue = this._Proveedor.Entity;
				if (((previousValue != value) 
							|| (this._Proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proveedor.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Proveedor.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._id_proveedor = value.Id_proveedor;
					}
					else
					{
						this._id_proveedor = default(int);
					}
					this.SendPropertyChanged("Proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proveedor")]
	public partial class Proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_proveedor;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Correo_Electronico;
		
		private EntitySet<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_proveedorChanging(int value);
    partial void OnId_proveedorChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCorreo_ElectronicoChanging(string value);
    partial void OnCorreo_ElectronicoChanged();
    #endregion
		
		public Proveedor()
		{
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_proveedor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_proveedor
		{
			get
			{
				return this._Id_proveedor;
			}
			set
			{
				if ((this._Id_proveedor != value))
				{
					this.OnId_proveedorChanging(value);
					this.SendPropertyChanging();
					this._Id_proveedor = value;
					this.SendPropertyChanged("Id_proveedor");
					this.OnId_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Correo Electronico]", Storage="_Correo_Electronico", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Correo_Electronico
		{
			get
			{
				return this._Correo_Electronico;
			}
			set
			{
				if ((this._Correo_Electronico != value))
				{
					this.OnCorreo_ElectronicoChanging(value);
					this.SendPropertyChanging();
					this._Correo_Electronico = value;
					this.SendPropertyChanged("Correo_Electronico");
					this.OnCorreo_ElectronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proveedor_Producto", Storage="_Producto", ThisKey="Id_proveedor", OtherKey="id_proveedor")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Proveedor = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Proveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Razas")]
	public partial class Razas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_raza;
		
		private string _nombre_raza;
		
		private EntitySet<Dogs> _Dogs;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_razaChanging(int value);
    partial void Oncod_razaChanged();
    partial void Onnombre_razaChanging(string value);
    partial void Onnombre_razaChanged();
    #endregion
		
		public Razas()
		{
			this._Dogs = new EntitySet<Dogs>(new Action<Dogs>(this.attach_Dogs), new Action<Dogs>(this.detach_Dogs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_raza", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cod_raza
		{
			get
			{
				return this._cod_raza;
			}
			set
			{
				if ((this._cod_raza != value))
				{
					this.Oncod_razaChanging(value);
					this.SendPropertyChanging();
					this._cod_raza = value;
					this.SendPropertyChanged("cod_raza");
					this.Oncod_razaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_raza", DbType="VarChar(20)")]
		public string nombre_raza
		{
			get
			{
				return this._nombre_raza;
			}
			set
			{
				if ((this._nombre_raza != value))
				{
					this.Onnombre_razaChanging(value);
					this.SendPropertyChanging();
					this._nombre_raza = value;
					this.SendPropertyChanged("nombre_raza");
					this.Onnombre_razaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Razas_Dogs", Storage="_Dogs", ThisKey="cod_raza", OtherKey="cod_raza")]
		public EntitySet<Dogs> Dogs
		{
			get
			{
				return this._Dogs;
			}
			set
			{
				this._Dogs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dogs(Dogs entity)
		{
			this.SendPropertyChanging();
			entity.Razas = this;
		}
		
		private void detach_Dogs(Dogs entity)
		{
			this.SendPropertyChanging();
			entity.Razas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_Id;
		
		private string _cedula_usuario;
		
		private string _nombre_usuario;
		
		private string _apellido_usuario;
		
		private string _user_name;
		
		private string _password;
		
		private string _correoE;
		
		private string _rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_IdChanging(int value);
    partial void Onuser_IdChanged();
    partial void Oncedula_usuarioChanging(string value);
    partial void Oncedula_usuarioChanged();
    partial void Onnombre_usuarioChanging(string value);
    partial void Onnombre_usuarioChanged();
    partial void Onapellido_usuarioChanging(string value);
    partial void Onapellido_usuarioChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OncorreoEChanging(string value);
    partial void OncorreoEChanged();
    partial void OnrolChanging(string value);
    partial void OnrolChanged();
    #endregion
		
		public Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_Id
		{
			get
			{
				return this._user_Id;
			}
			set
			{
				if ((this._user_Id != value))
				{
					this.Onuser_IdChanging(value);
					this.SendPropertyChanging();
					this._user_Id = value;
					this.SendPropertyChanged("user_Id");
					this.Onuser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cedula_usuario
		{
			get
			{
				return this._cedula_usuario;
			}
			set
			{
				if ((this._cedula_usuario != value))
				{
					this.Oncedula_usuarioChanging(value);
					this.SendPropertyChanging();
					this._cedula_usuario = value;
					this.SendPropertyChanged("cedula_usuario");
					this.Oncedula_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_usuario
		{
			get
			{
				return this._nombre_usuario;
			}
			set
			{
				if ((this._nombre_usuario != value))
				{
					this.Onnombre_usuarioChanging(value);
					this.SendPropertyChanging();
					this._nombre_usuario = value;
					this.SendPropertyChanged("nombre_usuario");
					this.Onnombre_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido_usuario
		{
			get
			{
				return this._apellido_usuario;
			}
			set
			{
				if ((this._apellido_usuario != value))
				{
					this.Onapellido_usuarioChanging(value);
					this.SendPropertyChanging();
					this._apellido_usuario = value;
					this.SendPropertyChanged("apellido_usuario");
					this.Onapellido_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correoE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string correoE
		{
			get
			{
				return this._correoE;
			}
			set
			{
				if ((this._correoE != value))
				{
					this.OncorreoEChanging(value);
					this.SendPropertyChanging();
					this._correoE = value;
					this.SendPropertyChanged("correoE");
					this.OncorreoEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this.OnrolChanging(value);
					this.SendPropertyChanging();
					this._rol = value;
					this.SendPropertyChanged("rol");
					this.OnrolChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vacunacion")]
	public partial class Vacunacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_vacunacion;
		
		private string _descripcion_vacunacion;
		
		private EntitySet<Dog_Vacu> _Dog_Vacu;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vacunacionChanging(int value);
    partial void Onid_vacunacionChanged();
    partial void Ondescripcion_vacunacionChanging(string value);
    partial void Ondescripcion_vacunacionChanged();
    #endregion
		
		public Vacunacion()
		{
			this._Dog_Vacu = new EntitySet<Dog_Vacu>(new Action<Dog_Vacu>(this.attach_Dog_Vacu), new Action<Dog_Vacu>(this.detach_Dog_Vacu));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vacunacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_vacunacion
		{
			get
			{
				return this._id_vacunacion;
			}
			set
			{
				if ((this._id_vacunacion != value))
				{
					this.Onid_vacunacionChanging(value);
					this.SendPropertyChanging();
					this._id_vacunacion = value;
					this.SendPropertyChanged("id_vacunacion");
					this.Onid_vacunacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_vacunacion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string descripcion_vacunacion
		{
			get
			{
				return this._descripcion_vacunacion;
			}
			set
			{
				if ((this._descripcion_vacunacion != value))
				{
					this.Ondescripcion_vacunacionChanging(value);
					this.SendPropertyChanging();
					this._descripcion_vacunacion = value;
					this.SendPropertyChanged("descripcion_vacunacion");
					this.Ondescripcion_vacunacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vacunacion_Dog_Vacu", Storage="_Dog_Vacu", ThisKey="id_vacunacion", OtherKey="id_vacunacion")]
		public EntitySet<Dog_Vacu> Dog_Vacu
		{
			get
			{
				return this._Dog_Vacu;
			}
			set
			{
				this._Dog_Vacu.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dog_Vacu(Dog_Vacu entity)
		{
			this.SendPropertyChanging();
			entity.Vacunacion = this;
		}
		
		private void detach_Dog_Vacu(Dog_Vacu entity)
		{
			this.SendPropertyChanging();
			entity.Vacunacion = null;
		}
	}
}
#pragma warning restore 1591
